### ISSUE TITLE
Compilation error in file HazelcastDciTopicToolFactory.groovy

### ISSUE THREAD

**Issue by igorgallingani** [moqui/moqui-hazelcast#1] opened 2017-01-16 11:05 UTC
The code below has an extra null argument:

 @Override
void onMessage(Message<EntityCacheInvalidate> message) {
            EntityCacheInvalidate eci = message.getMessageObject()
            // logger.info("====== EntityCacheListener message tenantId=${eci.tenantId} isCreate=${eci.isCreate}, evb: ${eci.evb}")
            ExecutionContextImpl.ThreadPoolRunnable runnable = new ExecutionContextImpl.ThreadPoolRunnable(ecfi, **null,** {
                ecfi.entityFacade.getEntityCache().clearCacheForValueActual(eci.evb, eci.isCreate)
            })
            ecfi.workerPool.execute(runnable)
        }

**Comment by jonesde** [comment] 2017-01-16 20:00
Thank you, this was caused by a recent change to moqui-framework. A fix is in commit #7e645a9.

**Closed by jonesde** 2017-01-16 20:00 UTC
